### ISSUE TITLE
[Doc] Version 1.23 Upgrade Handbook & Checklist

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#401]
### 打包

- [ ]  更新charts  kubegems/kubegems-installer  到 v1.23.0
- [ ]  更新内置应用商店镜像包 appstore-charts:v1.23.0
- [ ]  构建 AI 推理镜像列表，上传到百度云
- [ ]  构建 sealos 离线镜像包
